
# ENV variables below are found in .env
version: '3'

services:

  database:
    env_file: .env
    image: arangodb
    ports:
      - ${DB_PORT}:${DB_PORT}
    expose:
      - "${DB_PORT}"
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d

  api:
    env_file: .env
    build: ./
    image: auth-api
    ports:
      - ${API_PORT}:${API_PORT}
    command: "npm run start:containerized"
